# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 01:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_xworkflows.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom', '0001_initial'),
        ('bikes', '0001_initial'),
        ('tours', '__first__'),
        ('classes', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_type', models.CharField(blank=True, choices=[(b'bike', b'Bike'), (b'class', b'Class'), (b'class_bike', b'Class / Bike'), (b'custom', b'Custom'), (b'custom_bike', b'Custom / Bike'), (b'storage', b'Storage'), (b'tour', b'Tour'), (b'tour_bike', b'Tour / Bike')], max_length=20, null=True)),
                ('status', django_xworkflows.models.StateField(max_length=22, workflow=django_xworkflows.models._SerializedWorkflow(initial_state=b'pending_deposit', name=b'Workflow', states=[b'pending_deposit', b'reserved', b'checked_out', b'checked_in', b'pending_damage_payment']))),
                ('tour_room_type', models.CharField(blank=True, choices=[(b'Single', b'Single'), (b'Shared', b'Shared')], default=b'Shared', max_length=10, null=True)),
                ('storage_bike', models.CharField(blank=True, max_length=50, null=True)),
                ('checkout_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name=b'Check-Out')),
                ('checkin_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name=b'Check-In')),
                ('start', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('flexibility', models.CharField(blank=True, choices=[(5, '\xb15 Days'), (4, '\xb14 Days'), (3, '\xb13 Days'), (2, '\xb12 Days'), (1, '\xb11 Day'), (b'Exact', b'Exact')], default=b'Exact', max_length=20, null=True)),
                ('checkout_datetime_actual', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name=b'Check-Out (Actual)')),
                ('checkout_mileage', models.IntegerField(blank=True, null=True)),
                ('checkout_sketch', models.TextField(blank=True, null=True)),
                ('checkout_printed', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_signature', models.TextField(blank=True, null=True)),
                ('checkout_img_1', models.FileField(blank=True, null=True, upload_to=b'Check-Out/%Y/%m/')),
                ('checkout_img_2', models.FileField(blank=True, null=True, upload_to=b'Check-Out/%Y/%m/')),
                ('checkout_img_3', models.FileField(blank=True, null=True, upload_to=b'Check-Out/%Y/%m/')),
                ('checkout_img_4', models.FileField(blank=True, null=True, upload_to=b'Check-Out/%Y/%m/')),
                ('checkout_img_5', models.FileField(blank=True, null=True, upload_to=b'Check-Out/%Y/%m/')),
                ('checkout_img_6', models.FileField(blank=True, null=True, upload_to=b'Check-Out/%Y/%m/')),
                ('checkout_condition_complete', models.BooleanField(default=0)),
                ('checkout_bike_license_plate', models.CharField(blank=True, max_length=15, null=True)),
                ('checkout_membership_complete', models.BooleanField(default=0)),
                ('checkout_liability_complete', models.BooleanField(default=0)),
                ('checkout_notes', models.TextField(blank=True, null=True)),
                ('checkout_file_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('checkout_file_modified', models.DateTimeField(auto_now=True, null=True)),
                ('checkin_datetime_actual', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name=b'Check-In (Actual)')),
                ('checkin_mileage', models.IntegerField(blank=True, null=True)),
                ('is_damaged', models.BooleanField(default=0)),
                ('checkin_img_1', models.FileField(blank=True, null=True, upload_to=b'Check-In/%Y/%m/')),
                ('checkin_img_2', models.FileField(blank=True, null=True, upload_to=b'Check-In/%Y/%m/')),
                ('checkin_img_3', models.FileField(blank=True, null=True, upload_to=b'Check-In/%Y/%m/')),
                ('checkin_img_4', models.FileField(blank=True, null=True, upload_to=b'Check-In/%Y/%m/')),
                ('checkin_img_5', models.FileField(blank=True, null=True, upload_to=b'Check-In/%Y/%m/')),
                ('checkin_img_6', models.FileField(blank=True, null=True, upload_to=b'Check-In/%Y/%m/')),
                ('checkin_notes', models.TextField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name=b'Group Discount (%)')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=4, null=True, verbose_name=b'Tax Rate (%)')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('accessories', models.ManyToManyField(blank=True, to='bikes.Accessories')),
                ('bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bikes.Bike')),
                ('classes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Class')),
                ('custom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.Custom')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.Group')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Tour')),
            ],
            bases=(django_xworkflows.models.WorkflowEnabled, models.Model),
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('flexibility', models.CharField(blank=True, choices=[(5, '\xb15 Days'), (4, '\xb14 Days'), (3, '\xb13 Days'), (2, '\xb12 Days'), (1, '\xb11 Day'), (b'Exact', b'Exact')], default=b'Exact', max_length=20, null=True)),
                ('bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bikes.Bike')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.Reservation')),
            ],
        ),
    ]
