# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_auto_20160531_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='air_filter_clean_milage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='brake_fluid_change_milage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='coolant_change_milage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='current_milage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b'Bikes'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='oil_change_milage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='sprocket_and_chain_change_milage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='valve_adjustment_milage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
