# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 12:20
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_color', colorfield.fields.ColorField(default=b'#999999', max_length=10, null=True)),
                ('custom_ride_1day_price', models.IntegerField(blank=True, null=True)),
                ('custom_ride_2day_price', models.IntegerField(blank=True, null=True)),
                ('custom_ride_6day_price', models.IntegerField(blank=True, null=True)),
                ('bike_deposit', models.IntegerField(blank=True, null=True)),
                ('tour_deposit', models.IntegerField(blank=True, null=True)),
                ('tour_deposit_due_lead_time', models.IntegerField(blank=True, null=True, verbose_name=b'Tour Deposit Due Lead Time (Days)')),
                ('bike_damage_deposit', models.IntegerField(blank=True, null=True)),
                ('insurance_price', models.IntegerField(blank=True, null=True)),
                ('storage_price', models.IntegerField(blank=True, null=True)),
                ('calendar_color_tour', colorfield.fields.ColorField(default=b'#999999', max_length=10, null=True)),
                ('calendar_color_class', colorfield.fields.ColorField(default=b'#999999', max_length=10, null=True)),
                ('calendar_color_bike', colorfield.fields.ColorField(default=b'#999999', max_length=10, null=True)),
                ('calendar_color_storage', colorfield.fields.ColorField(default=b'#999999', max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Preference',
            },
        ),
    ]
