# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='bike_deposit',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Bike Deposit - Daily Rate'),
        ),
    ]
