# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20160531_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='bike_deposit',
            new_name='bike_deposit_multiple',
        ),
    ]
