# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('bike', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bikes.Bike')),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Guide',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_start', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('date_end', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('skill', models.IntegerField(blank=True, choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5')], default=3, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('price_shared', models.IntegerField(blank=True, null=True, verbose_name=b'Price (Shared)')),
                ('price_single', models.IntegerField(blank=True, null=True, verbose_name=b'Price (Single)')),
                ('deposit', models.IntegerField(blank=True, default=1000, null=True, verbose_name=b'Reservation Deposit')),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Guide')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Location')),
            ],
        ),
        migrations.CreateModel(
            name='TourAccessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('price_period', models.CharField(blank=True, choices=[(b'One-Time', b'One-Time'), (b'Daily', b'Daily'), (b'Hourly', b'Hourly'), (b'Monthly', b'Monthly'), (b'Bi-Annual', b'Bi-Annual'), (b'Annual', b'Annual')], default=b'One-Time', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tour Accessories',
            },
        ),
        migrations.CreateModel(
            name='TourPlanning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(blank=True, choices=[(b'Pending', b'Pending'), (b'In-progress', b'In-Progress'), (b'Complete', b'Complete')], default=b'pending', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='bikeprice',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Tour'),
        ),
    ]
